package ebpftracer

import (
	"bytes"
	"encoding/binary"
	"errors"
	"os"
	"os/exec"
	"path"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	"github.com/coroot/coroot-node-agent/common"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/sys/unix"
)

func TestParsePidNsInum(t *testing.T) {
	inum, err := parsePidNsInum("pid:[4026531836]")
	require.NoError(t, err)
	assert.Equal(t, uint32(4026531836), inum)

	inum, err = parsePidNsInum("pid:[4026532567]")
	require.NoError(t, err)
	assert.Equal(t, uint32(4026532567), inum)

	for _, invalid := range []string{"", "pid:[]", "pid:4026531836", "net:[4026531836]", "pid:[abc]", "pid:[4026531836"} {
		_, err = parsePidNsInum(invalid)
		assert.Error(t, err, invalid)
	}
}

func TestReadPidNsInum(t *testing.T) {
	dir := t.TempDir()
	link := path.Join(dir, "pid")
	require.NoError(t, os.Symlink("pid:[4026532567]", link))

	inum, err := readPidNsInum(link)
	require.NoError(t, err)
	assert.Equal(t, uint32(4026532567), inum)

	_, err = readPidNsInum(path.Join(dir, "missing"))
	assert.Error(t, err)
}

func TestTranslationTarget(t *testing.T) {
	dir := t.TempDir()

	nested := path.Join(dir, "nested")
	require.NoError(t, os.Symlink("pid:[4026532567]", nested))
	inum, err := translationTarget(nested)
	require.NoError(t, err)
	assert.Equal(t, uint32(4026532567), inum)

	// the initial namespace needs no translation
	initial := path.Join(dir, "initial")
	require.NoError(t, os.Symlink("pid:[4026531836]", initial))
	inum, err = translationTarget(initial)
	require.NoError(t, err)
	assert.Zero(t, inum)

	_, err = translationTarget(path.Join(dir, "missing"))
	assert.Error(t, err)
}

func TestSelectProg(t *testing.T) {
	progs := []ebpfProg{
		{"5.12", "core,ctx-extra-padding", []byte("512-core-cep")},
		{"5.12", "core", []byte("512-core")},
		{"5.12", "ctx-extra-padding", []byte("512-cep")},
		{"5.12", "", []byte("512")},
		{"5.6", "core", []byte("506-core")},
		{"5.6", "", []byte("506")},
		{"4.20", "", []byte("420")},
		{"4.16", "", []byte("416")},
	}

	version := func(s string) common.Version {
		v, err := common.VersionFromString(s)
		require.NoError(t, err)
		return v
	}

	for _, tc := range []struct {
		name            string
		kernel          string
		ctxExtraPadding bool
		btf             bool
		want            string
	}{
		{"btf prefers the CO-RE variant", "6.8.0", false, true, "512-core"},
		{"no btf falls back to the plain variant", "6.8.0", false, false, "512"},
		{"btf with extra padding", "6.8.0", true, true, "512-core-cep"},
		{"no btf with extra padding", "6.8.0", true, false, "512-cep"},
		{"btf on a kernel with no CO-RE variant", "4.19.0", false, true, "416"},
		{"btf picks the newest matching CO-RE variant", "5.6.0", false, true, "506-core"},
		{"unsupported kernel", "4.15.0", false, true, ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := selectProg(progs, version(tc.kernel), tc.ctxExtraPadding, tc.btf)
			assert.Equal(t, tc.want, string(got))
		})
	}
}

// TestEmbeddedProgs checks the objects generated by ebpftracer/Dockerfile: the CO-RE
// ones have to expose the constant the agent writes its PID namespace to and read the
// child task through a raw tracepoint, while the plain ones must keep neither.
func TestEmbeddedProgs(t *testing.T) {
	require.NotEmpty(t, ebpfProgs)

	for arch, progs := range ebpfProgs {
		var core int
		for _, p := range progs {
			t.Run(arch+"/"+p.version+"/"+p.flags, func(t *testing.T) {
				obj, err := decodeProg(p.prog)
				require.NoError(t, err)
				spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(obj))
				require.NoError(t, err)

				taskNewtask := spec.Programs["task_newtask"]
				require.NotNil(t, taskNewtask)

				if !strings.HasPrefix(p.flags, progFlagCore) {
					assert.Nil(t, spec.Variables[agentPidNsVar])
					assert.Equal(t, ebpf.TracePoint, taskNewtask.Type)
					assert.Equal(t, "task/task_newtask", taskNewtask.AttachTo)
					return
				}
				core++
				require.NotNil(t, spec.Variables[agentPidNsVar])
				assert.True(t, spec.Variables[agentPidNsVar].Constant())
				assert.Equal(t, uint64(4), spec.Variables[agentPidNsVar].Size())
				assert.NoError(t, spec.Variables[agentPidNsVar].Set(uint32(4026532567)))
				assert.Equal(t, ebpf.RawTracepoint, taskNewtask.Type)
				assert.Equal(t, "task_newtask", taskNewtask.AttachTo)
			})
		}
		assert.NotZero(t, core, "%s has no CO-RE variant", arch)
	}
}

// TestLoadCoreProgs pushes every CO-RE object through the verifier of the running
// kernel, which is the only place the relocations in ebpf/pidns.h are actually
// resolved, and attaches the raw tracepoint. Needs root and kernel BTF.
func TestLoadCoreProgs(t *testing.T) {
	if os.Getenv("VM") == "" {
		t.SkipNow()
	}
	if !kernelBTFAvailable() {
		t.Skipf("%s is not available, the CO-RE objects cannot be loaded here", kernelBTFPath)
	}
	_ = unix.Setrlimit(unix.RLIMIT_MEMLOCK, &unix.Rlimit{Cur: unix.RLIM_INFINITY, Max: unix.RLIM_INFINITY})

	progs := ebpfProgs[runtime.GOARCH]
	require.NotEmpty(t, progs)

	var tested int
	for _, p := range progs {
		if !strings.HasPrefix(p.flags, progFlagCore) {
			continue
		}
		t.Run(p.version+"/"+p.flags, func(t *testing.T) {
			obj, err := decodeProg(p.prog)
			require.NoError(t, err)
			spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(obj))
			require.NoError(t, err)
			require.NoError(t, setAgentPidNs(spec))

			c, err := ebpf.NewCollection(spec)
			var vErr *ebpf.VerifierError
			if errors.As(err, &vErr) {
				t.Fatalf("%+v", vErr)
			}
			require.NoError(t, err)
			defer c.Close()

			l, err := link.AttachRawTracepoint(link.RawTracepointOptions{
				Name:    "task_newtask",
				Program: c.Programs["task_newtask"],
			})
			require.NoError(t, err)
			require.NoError(t, l.Close())
		})
		tested++
	}
	assert.NotZero(t, tested)
}

// TestPidTranslation is the point of the whole change: started from inside a nested
// PID namespace it asserts that process events carry the PID the agent itself would
// use to look the process up in /proc, not the one of the root namespace.
//
// Needs root, kernel BTF and a PID namespace of its own, so in practice a privileged
// container: docker run --privileged -e VM=1 ...
func TestPidTranslation(t *testing.T) {
	if os.Getenv("VM") == "" {
		t.SkipNow()
	}
	inum, err := readPidNsInum(selfPidNsPath)
	require.NoError(t, err)
	if inum == initPidNsInum {
		t.Skip("running in the initial pid namespace, nothing to translate")
	}
	require.True(t, kernelBTFAvailable(), "%s is required", kernelBTFPath)
	_ = unix.Setrlimit(unix.RLIMIT_MEMLOCK, &unix.Rlimit{Cur: unix.RLIM_INFINITY, Max: unix.RLIM_INFINITY})

	var uname unix.Utsname
	require.NoError(t, unix.Uname(&uname))
	release := string(bytes.SplitN(uname.Release[:], []byte{0}, 2)[0])
	require.NoError(t, common.SetKernelVersion(release))

	prog := selectProg(ebpfProgs[runtime.GOARCH], common.GetKernelVersion(), false, true)
	require.NotEmpty(t, prog)
	obj, err := decodeProg(prog)
	require.NoError(t, err)
	spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(obj))
	require.NoError(t, err)
	require.NotNil(t, spec.Variables[agentPidNsVar], "the CO-RE variant was not selected")
	require.NoError(t, setAgentPidNs(spec))

	c, err := ebpf.NewCollection(spec)
	require.NoError(t, err)
	defer c.Close()

	l, err := link.AttachRawTracepoint(link.RawTracepointOptions{
		Name:    "task_newtask",
		Program: c.Programs["task_newtask"],
	})
	require.NoError(t, err)
	defer l.Close()

	r, err := perf.NewReader(c.Maps["proc_events"], 8*os.Getpagesize())
	require.NoError(t, err)
	defer r.Close()

	cmd := exec.Command("/bin/sleep", "0")
	require.NoError(t, cmd.Start())
	want := uint32(cmd.Process.Pid)
	require.NoError(t, cmd.Wait())

	// Nothing but a correct translation can produce this number: it is the PID of
	// our namespace, and the same task carries an entirely different one in the root
	// namespace the programs observe. Without the translation the loop below runs
	// out of time and reports the untranslated PIDs it did see.
	var seen []uint32
	deadline := time.Now().Add(10 * time.Second)
	for {
		r.SetDeadline(deadline)
		rec, err := r.Read()
		if err != nil {
			t.Fatalf("no process-start event for pid %d (%s), saw %v", want, err, seen)
		}
		var e procEvent
		require.NoError(t, binary.Read(bytes.NewReader(rec.RawSample), binary.LittleEndian, &e))
		if e.Type != EventTypeProcessStart {
			continue
		}
		if e.Pid == want {
			return
		}
		seen = append(seen, e.Pid)
	}
}

func TestSelectProgFallsBackWhenCoreVariantIsMissing(t *testing.T) {
	// a build without any CO-RE objects must keep working on a BTF-capable host
	progs := []ebpfProg{
		{"5.12", "ctx-extra-padding", []byte("512-cep")},
		{"5.12", "", []byte("512")},
	}
	v, err := common.VersionFromString("6.8.0")
	require.NoError(t, err)

	assert.Equal(t, "512", string(selectProg(progs, v, false, true)))
	assert.Equal(t, "512-cep", string(selectProg(progs, v, true, true)))
}
