package ebpftracer

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	"github.com/cilium/ebpf"
	"github.com/coroot/coroot-node-agent/common"
	"k8s.io/klog/v2"
)

// agentPidNsVar is the .rodata constant the CO-RE objects read the agent's PID
// namespace from.
const agentPidNsVar = "agent_pidns_inum"

// initPidNsInum is the inode the kernel hands out to the initial PID namespace
// (PROC_PID_INIT_INO).
const initPidNsInum = 0xEFFFFFFC

// Program variant flags. They must match the flags emitted by ebpftracer/Dockerfile.
const (
	progFlagCtxExtraPadding = "ctx-extra-padding"
	progFlagCore            = "core"
	progFlagCoreAndPadding  = "core,ctx-extra-padding"
)

// selfPidNsPath is the magic symlink pointing to the PID namespace of the agent itself.
const selfPidNsPath = "/proc/self/ns/pid"

// kernelBTFPath is where the kernel exposes its own BTF. CO-RE relocations cannot
// be resolved without it.
const kernelBTFPath = "/sys/kernel/btf/vmlinux"

// ebpfProg is a single precompiled eBPF object. The ebpfProgs variable holding them
// is generated by ebpftracer/Dockerfile.
type ebpfProg struct {
	version string
	flags   string
	prog    []byte
}

// parsePidNsInum extracts the namespace inode from the target of a /proc/<pid>/ns/pid
// symlink, which the kernel formats as "pid:[4026531836]".
func parsePidNsInum(link string) (uint32, error) {
	rest, ok := strings.CutPrefix(link, "pid:[")
	if !ok {
		return 0, fmt.Errorf("unexpected pid ns link: %q", link)
	}
	rest, ok = strings.CutSuffix(rest, "]")
	if !ok {
		return 0, fmt.Errorf("unexpected pid ns link: %q", link)
	}
	inum, err := strconv.ParseUint(rest, 10, 32)
	if err != nil {
		return 0, fmt.Errorf("unexpected pid ns link: %q", link)
	}
	return uint32(inum), nil
}

func readPidNsInum(path string) (uint32, error) {
	link, err := os.Readlink(path)
	if err != nil {
		return 0, err
	}
	return parsePidNsInum(link)
}

// decodeProg unpacks one of the objects embedded in the generated ebpf.go.
func decodeProg(prog []byte) ([]byte, error) {
	reader, err := gzip.NewReader(base64.NewDecoder(base64.StdEncoding, bytes.NewReader(prog)))
	if err != nil {
		return nil, fmt.Errorf("invalid program encoding: %w", err)
	}
	prog, err = io.ReadAll(reader)
	if err != nil {
		return nil, fmt.Errorf("failed to ungzip program: %w", err)
	}
	return prog, nil
}

// translationTarget returns the PID namespace the programs should report PIDs in,
// or 0 when there is nothing to translate. In the initial namespace the PIDs the
// programs observe are already the ones the agent resolves through /proc, so it is
// left disabled to keep events off the struct pid walk entirely.
func translationTarget(pidNsPath string) (uint32, error) {
	inum, err := readPidNsInum(pidNsPath)
	if err != nil {
		return 0, fmt.Errorf("failed to read %s: %w", pidNsPath, err)
	}
	if inum == initPidNsInum {
		return 0, nil
	}
	return inum, nil
}

// setAgentPidNs tells a CO-RE object which PID namespace to report PIDs in. The
// plain objects carry no such variable and are left untouched.
func setAgentPidNs(spec *ebpf.CollectionSpec) error {
	v := spec.Variables[agentPidNsVar]
	if v == nil {
		return nil
	}
	inum, err := translationTarget(selfPidNsPath)
	if err != nil {
		return err
	}
	if inum == 0 {
		return nil
	}
	if err = v.Set(inum); err != nil {
		return fmt.Errorf("failed to set %s: %w", agentPidNsVar, err)
	}
	klog.Infof("running in a nested pid namespace, reporting PIDs as seen from %d", inum)
	return nil
}

// kernelBTFAvailable reports whether the running kernel exposes its own BTF.
func kernelBTFAvailable() bool {
	fi, err := os.Stat(kernelBTFPath)
	return err == nil && fi.Size() > 0
}

// selectProg picks the most specific precompiled object for the running kernel.
//
// A CO-RE build translates PIDs into the namespace of the agent, which is what makes
// nested setups such as kind work. It needs kernel BTF, so whenever BTF is unavailable
// - or the build simply carries no CO-RE object for this kernel - the plain object is
// used and the agent behaves exactly as it did before.
func selectProg(progs []ebpfProg, kernelVersion common.Version, ctxExtraPadding bool, btf bool) []byte {
	var candidates []string
	if btf {
		if ctxExtraPadding {
			candidates = append(candidates, progFlagCoreAndPadding)
		} else {
			candidates = append(candidates, progFlagCore)
		}
	}
	if ctxExtraPadding {
		candidates = append(candidates, progFlagCtxExtraPadding)
	} else {
		candidates = append(candidates, "")
	}

	for _, flags := range candidates {
		for _, p := range progs {
			if p.flags != flags {
				continue
			}
			v, err := common.VersionFromString(p.version)
			if err != nil {
				continue
			}
			if !kernelVersion.GreaterOrEqual(v) {
				continue
			}
			return p.prog
		}
	}
	return nil
}
